# 
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "7.3.9"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: admin

    persistence:
      enabled: true
      size: 10Gi

    service:
      type: ClusterIP
      port: 3000

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - app-monitor.local
      paths:
        - /

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki.monitoring.svc.cluster.local:3100
            access: proxy

    dashboards:
      default:
        wordpress-logs:
          gnetId: 0
          revision: 1
          datasource: Loki
          url: https://raw.githubusercontent.com/grafana/grafana/main/public/dashboards/nginx.json

    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
