#
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.42.0"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi

    test:
      enabled: false
