# applications/ingress-nginx/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.7"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
      interval: 1m
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
      resources:
        limits:
          cpu: 200m
          memory: 90Mi
        requests:
          cpu: 100m
          memory: 90Mi

      # ---- USE OPENRESTY IMAGE WITH LUA ----
      image:
        repository: ingress-nginx/kube-webhook-certgen
        tag: v20240911-controller-v1.11.2-2-g9f85c5c2f@sha256:8b240...
        # NO: Use the OpenResty-based controller
        # YES: Override with OpenResty image
      extraArgs:
        - --enable-ssl-chain-completion=false

      # ---- MOUNT LUA SCRIPTS ----
      extraVolumes:
        - name: lua-scripts
          configMap:
            name: nginx-lua-scripts
            defaultMode: 493
      extraVolumeMounts:
        - name: lua-scripts
          mountPath: /etc/nginx/lua/
          readOnly: true

      # ---- CONFIG ----
      config:
        allow-snippet-annotations: "true"
        lua-package-path: "/etc/nginx/lua/?.lua;;"
        load-module: /usr/local/lib/lua/5.1/resty.so  # if needed

        # These are now valid because we use OpenResty
        http-snippet: |
          init_by_lua_block {
            require("404-redirect")
          }

        server-snippet: |
          header_filter_by_lua_block {
            if ngx.status == 404 then
              ngx.header["Location"] = "https://google.com"
              ngx.status = 302
              ngx.header.content_length = nil
              ngx.exit(ngx.HTTP_OK)
            end
          }

        ssl-ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"

    admissionWebhooks:
      enabled: false

    # ---- CRITICAL: Use OpenResty-based controller image ----
    # The default image is NOT OpenResty
    # Use the official OpenResty build from ingress-nginx
    controller:
      image:
        repository: registry.k8s.io/ingress-nginx/controller
        tag: v1.11.2
        pullPolicy: IfNotPresent
      kind: Deployment
      # BUT: We need OpenResty → use custom image
      # SEE BELOW
