# /path/to/your/git/repo/releases/nginx-ingress-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  interval: 5m

  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.7" # Use the latest stable version, e.g., 4.8.3
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
      interval: 1m

  # Example values overrides to customize the installation
  values:
    controller:
      replicaCount: 1 # Adjust based on your needs
      service:
        type: LoadBalancer # Or NodePort, depending on your infrastructure
        # If using LoadBalancer, you might specify annotations or loadBalancerIP
        # annotations:
        #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        # loadBalancerIP: "x.x.x.x" # Specific IP if supported by your cloud provider
      config:
        # Example: Enable use-proxy-protocol (cloud-specific)
        # use-proxy-protocol: "true"
        # Example: Set default SSL cipher suites
        ssl-ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
      # Resources (optional but recommended for production)
      resources:
        limits:
          cpu: 200m
          memory: 90Mi
        requests:
          cpu: 500m
          memory: 90Mi
    # Default backend (optional, can be disabled if not needed)
    # defaultBackend:
    #   enabled: true
    #   image:
    #     repository: k8s.gcr.io/defaultbackend-amd64
    #     tag: "1.5"
    #   resources:
    #     limits:
    #       cpu: 10m
    #       memory: 20Mi
    #     requests:
    #       cpu: 10m
    #       memory: 20Mi
