apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.7"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
      interval: 1m
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
      config:
        ssl-ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
        # Enable Lua and load our custom script
        allow-snippet-annotations: "true"
        http-snippet: |
          lua_package_path "/etc/nginx/lua/?.lua;;";
          init_by_lua_block {
            require("404-redirect")
          }
      # Mount the Lua scripts
      extraVolumeMounts:
        - name: lua-scripts
          mountPath: /etc/nginx/lua/404-redirect.lua
          subPath: 404-redirect.lua
      # Global 404 redirect for all servers
      serverSnippet: |
        header_filter_by_lua_block {
          if ngx.status == 404 then
            ngx.header["Location"] = "https://google.com"
            ngx.status = 302
            ngx.header.content_length = nil
          end
        }
      resources:
        limits:
          cpu: 200m
          memory: 90Mi
        requests:
          cpu: 100m
          memory: 90Mi
    # Mount the ConfigMap as volume
    extraVolumes:
      - name: lua-scripts
        configMap:
          name: nginx-lua-scripts
    # Disable admission webhooks to avoid issues
    admissionWebhooks:
      enabled: false
