apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-stable
  namespace: ingress-nginx # This must match the namespace of your HelmRelease
spec:
  interval: 10m
  url: https://kubernetes.github.io/ingress-nginx
